name: toocans
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  flutter_easyloading: ^3.0.5
#  image_gallery_saver: ^2.0.3 # 保存视频和图片到手机相册
  connectivity_plus: ^6.1.1
#  easy_localization: ^3.0.0  # 国际化
#  # flustars很久不维护，可以使用这个替代 https://pub.flutter-io.cn/packages/flustars_flutter3
  flustars_flutter3: ^3.0.0
  # 加密本地保存 https://pub.dev/packages/encrypt_shared_preferences
  encrypt_shared_preferences: ^0.8.4
  # https://pub.dev/packages/get
  get: ^4.6.6
  # https://pub.dev/packages/flutter_screenutil
  flutter_screenutil: ^5.9.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true
#  assets:
#    - assets/lang/
#    - assets/images/
#    - assets/images/profile/
#    - assets/images/profile/2.0x/
#    - assets/images/profile/3.0x/
#    - assets/images/loading.gif

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


